insert into burgers (burger_name, devoured) values 
	("Rest in Peas Burger",false),
	("Fig-eta Bout It Burger",false),
	("Last of the Mo-Jicama Burger",false),
	("Olive and Let Die Burger",false),
	("Poblano Picasso Burger",false),
	("Salvador Cauliflower Burger",false),
	("Shoot Out at the Okra Corral Burger",false),
	("Hit Me With Your Best Shallot Burger",false),
	("I've Created a Meunster Burger",false),
	("Neither Fish Nor Fowl Burger",false),
	("One Fish, Two Fish, Red Fish Hamburger",false),
	("Chard to a Crisp Burger",false),
	("Good Night and Good Leek Burger",false),
	("Chorizo Your Own Adventure Burger",false),
	("Poutine on the Ritz Burger",false),
	("Summer Thyme Burger",false),
	("Butterface Burger",false),
	("Beets Me Burger",false),
	("We're Here, We're Gruyere Burger",false),
	("Chipotle Off the Old Block Burger",false),
	("One Horse Open Slaw Burger",false),
	("Home for the Challah-Days Burger",false);